name: build

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install
      - run: npm run lint
      - run: npm run coverage
      - run: npm run lcov
      - uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ github.token }}

